# Generated by Django 5.0.1 on 2024-02-01 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        max_length=36, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[("L", "L"), ("R", "R"), ("Ln", "ln")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("center_distance", models.PositiveIntegerField(default=0)),
                ("verification_interval", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeterVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meters.meter"
                    ),
                ),
            ],
        ),
    ]
