# Generated by Django 5.0.1 on 2024-02-05 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meter",
            name="code",
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="MeterAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meters.meter"
                    ),
                ),
            ],
        ),
    ]
