# Generated by Django 5.0.1 on 2024-02-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_meter_code_meteraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
