version: '3.8'

services:
  api:
    build:
      context: ./django_inventory/.
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=$DEBUG
      - SECRET_KEY=$SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS
      - CSRF_TRUSTED_ORIGINS=$CSRF_TRUSTED_ORIGINS
      - FRONTEND_URL=$FRONTEND_URL
      - SQL_ENGINE=$SQL_ENGINE
      - SQL_DATABASE=$SQL_DATABASE
      - SQL_USER=$SQL_USER
      - SQL_PASSWORD=$SQL_PASSWORD
      - SQL_HOST=$SQL_HOST
      - SQL_PORT=$SQL_PORT

  web:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL


