version: '3.8'

services:
  api:
    build:
      context: ./django_inventory/.
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./django_inventory/.env.dev
    depends_on:
      - db

  web:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./django_inventory/.env.db

volumes:
  postgres_data:

