version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && gunicorn django_inventory.wsgi:application --bind 0.0.0.0:8000 && python manage.py collectstatic"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
